[project]
name = "Montreal-Agent"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.18",
    "fastapi>=0.115.12",
    "fastmcp>=2.3.3",
    "mcp[cli]>=1.8.0",
    "praw>=7.8.1",
    "python-dotenv>=1.1.0",
]
